
<!DOCTYPE html>
<html>
<head>
   <title>Twiddit</title>
   <!-- Latest compiled and minified CSS -->
   <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
   <link rel="stylesheet" type='text/css' href="/public/css/base.css">
   <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
   <nav class="navbar navbar-default">
     <div class="container-fluid">
       <!-- Brand and toggle get grouped for better mobile display -->
       <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
         <a class="navbar-brand" href="#">Twiddit</a>
       </div>

       <!-- Collect the nav links, forms, and other content for toggling -->
       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
         <ul class="nav navbar-nav">
         <li id="following_tab" class="view_tab active" data-viewid="following_feed"><a href="#">People/Following<span class="sr-only">(current)</span></a></li>
           <li id="subreddits_tab" class="view_tab" data-viewid="subreddits_feed"><a href="#">Subreddits</a></li>
           <li id="preferences_tab" class="view_tab" data-viewid="preferences_page"><a href="#">Preferences</a></li>
           <li id="messaging_tab" class="view_tab" data-viewid="messaging_page"><a href="#">Messaging</a></li>
         </ul>
         <ul class="nav navbar-nav navbar-right">
           <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><?= $user ?><span class="caret"></span></a>
             <ul class="dropdown-menu" role="menu">
               <li><a href="#">Favorites</a></li>
               <li class="divider"></li>
               <li id='logout'><a href="#">Log Out</a></li>
             </ul>
           </li>
         </ul>
       </div><!-- /.navbar-collapse -->
     </div><!-- /.container-fluid -->
   </nav>
   <div id="loading_area">
      <img src='/public/img/loading.gif'/>
      <h3 class='lead'>Building your content...</h3>
   </div>
   <div id='following_feed' class='container'>
      <h2 class='section_title'>Redditors You Follow</h2>
      <div class='container section_body'></div>
   </div>
   <div id='subreddits_feed' class='container'>
      <h2 class='section_title'>Subreddits You Follow</h2>
      <div class='container section_body'></div>
   </div>
   <div id='preferences_page' class="container">
      <div class="row">
         <div class="col-lg-12">
            <h1>Preferences</h1>
            <div class="container-fluid">
               <div id="following-prefs" class="preference-body" style="width:275px;">
                   <h3>People You Follow</h3>
                   <ul id="following" class="list-unstyled"></ul>
               </div>
               <form class="form-search">
                  <input id="uSearch" type="text" class="input-medium" placeholder="Follow someone new">
                  <button id="uButton" class="btn">Follow</button>
               </form>
               <h3>Subreddits You Follow</h3>
               <div id="subreddit-prefs" class="preference-body" "style="width:250px;"></div>
               <form class="form-search">
                  <input id="rSearch" type="text" class="input-medium" placeholder="Follow a new subreddit">
                  <button id="rButton" class="btn">Follow</button>
               </form>
               <h3>Login with Reddit</h3>
               <p>This allows you to favorite posts and send private messages to other redditors</p>
               <a href='<?= $oauthUrl ?>'><button type="button" class="btn btn-primary">Connect to Reddit</button></a>
            </div>
        </div>
      </div><!-- /.row -->
   </div>
   <div id="messaging_page" class="container">
      <form>
        <div class="form-group">
          <label for="message_recipient">To</label>
          <input type="text" class="form-control" id="message_recipient" placeholder="Who's this to?">
        </div>
        <div class="form-group">
          <label for="message_subject">Subject</label>
          <input type="text" class="form-control" id="message_subject" placeholder="What's it about?">
        </div>
        <div class="form-group">
          <label for="message_body">Message</label>
          <textarea class="form-control" id="message_body" placeholder="Hey There!" style="width:400px; height:100px"></textarea>
         </div>
         <button id="message_send" class="btn btn-default">Send</button>
         <span id="message_result"></span>
      </form>
   </div>

   <!-- Defer JS for last -->
   <!-- jQuery library -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
   <!-- Latest compiled JavaScript -->
   <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
   <!-- Our view logic -->
   <script src='/public/js/app.js'></script>
</body>
</html>
